# Generated by Django 4.2.6 on 2024-02-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='majors',
            new_name='major',
        ),
    ]
