# Generated by Django 4.2.6 on 2024-02-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='majors',
            field=models.CharField(choices=[('cntt', 'Công Nghệ Thông Tin'), ('cnsh', 'Công Nghệ Sinh Học'), ('kdqt', 'Kinh Doanh Quốc Tế')], default='cntt', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sinhvien', 'Sinh Viên'), ('giangvien', 'Giảng Viên'), ('giaovukhoa', 'Giáo Vụ Khoa')], default='sinhvien', max_length=255),
        ),
    ]
