# Generated by Django 4.2.6 on 2024-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
